config/routes.rb
Rails.application.routes.draw do

  resources 'games', only: [:index] do
    member do
      get 'scoreboard'
    end
  end

  resources 'users', except: :index
  resources 'submissions', except: :index

  get '/submit', to: 'submissions#new'
  get '/scoreboard', to: 'home#scoreboard'
  get '/player_scoreboard/:id', to: 'home#player_scoreboard', as: 'player_scoreboard'
  get '/submissionsonlywolf', to: 'submissions#index'
  get '/playersonlywolf', to: 'users#index'
  
  root to: 'home#index'

end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :submissions
  scope :tournament_one, -> { where(tournament_id: nil) }
  scope :scoreboard, -> (user_id) { joins(:submissions).select("games.id, games.name, MAX(score) as max_score, MAX(submissions.created_at) as creat_at").where("submissions.user_id = ? AND games.tournament_id IS NULL", user_id).order("games.name ASC").group("games.id, games.name")}
end

app/models/submission.rb
class Submission < ActiveRecord::Base
  belongs_to :user
  belongs_to :game
  validates_presence_of :user_id, :game_id
  validates :score, numericality: { only_integer: true, message: "Should be a number!" }

  scope :tournament_one, -> { where("user_id < 74") }

  LATEST = 7
end

app/models/team.rb
class Team < ActiveRecord::Base
  has_many :users
  belongs_to :tournament
end

app/models/tournament.rb
class Tournament < ActiveRecord::Base
  has_many :games
  has_many :users
  has_many :teams
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :submissions

  scope :tournament_one, -> { where(tournament_id: nil) }

  scope :scoreboard, -> (game_id) { joins(:submissions).select("users.id, users.name, MAX(score) as max_score, MAX(submissions.created_at) as creat_at").where("submissions.game_id = ? AND users.tournament_id IS NULL", game_id).order("max_score DESC, creat_at ASC").group("users.id, users.name")}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Game.tournament_one.order('name ASC')
  end

  def scoreboard
    @game       = Game.find(params.fetch(:id))
    @players    = User.scoreboard(@game.id)
    @latest_sub = @game.submissions.order("submissions.created_at DESC").limit(Submission::LATEST)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def scoreboard
    @players    = FetchMainScoreboard.call
    @latest_sub = Submission.tournament_one.order("created_at DESC").limit(Submission::LATEST)
  end

  def player_scoreboard
    @player     = User.find(params.fetch(:id))
    @games      = Game.scoreboard(@player.id)
    @latest_sub = @player.submissions.order("submissions.created_at DESC").limit(Submission::LATEST)
  end
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController

  before_filter :fetch_players_and_games, only: [:new, :create]

  def new
    @submission = Submission.new(user_id: cookies[:player_id])
  end

  def create
    @submission = Submission.new(submission_params)
    @submission.ip_address = request.remote_ip
    if @submission.save
      set_player_cookie
      redirect_to scoreboard_game_path(@submission.game), notice: "Good Luck!"
    else
      render "new"
    end
  end

  private

  def submission_params
    params.require(:submission).permit(:user_id, :game_id, :score)
  end

  def fetch_players_and_games
    @players = User.tournament_one.order('name ASC')
    @games   = Game.tournament_one.order('name ASC')
  end

  def set_player_cookie
    if cookies[:player_id] != @submission.user_id
      cookies[:player_id] = @submission.user_id
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @tournament = Tournament.find(2)
    @users = @tournament.users.order("team_id ASC, name ASC")
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @user.tournament_id = 2
    respond_to do |format|
      if @user.save
        format.html { redirect_to playersonlywolf_path, notice: 'Player was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to playersonlywolf_path, notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to playersonlywolf_url, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params[:user].permit(:name, :team_id, :tournament_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def main_title
    request.user_agent =~ /Mobile|webOS/ ? "Yolympics" : "Yolympics"
  end

end

app/helpers/games_helper.rb
module GamesHelper

  def button_link(link, text, style='', target='')
    link_to(content_tag(:div, text, class: "btn #{style} pull-right link-ru"), link, target: "#{target}") 
  end
end

app/helpers/home_helper.rb
module HomeHelper

  def player_submission(submission)
    "#{submission.user.name} <span class='small'>playing</span> #{link_to(submission.game.name, scoreboard_game_path(submission.game))}".html_safe
  end

end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_flash.html.haml
.flash
  -if flash[:notice].present?
    .alert.alert-dismissable.alert-success{role: "alert"}
      = flash[:notice]

  -if flash[:error].present?
    .alert.alert-dismissable.alert-danger{role: "alert"}
      =flash[:error]

  -if flash[:warning].present?
    .alert.alert-dismissable.alert-warning{role: "alert"}
      =flash[:warning]

app/views/application/_footer.html.haml
.navbar.navbar-default.navbar-fixed-bottom
  .container
    .navbar-text.pull-left Built by AlexGunslinger

app/views/games/index.html.haml
.page-header
  %h1.text-center Games

.game-list
  .row
    .col-xs-15
      .games-container
        - @games.in_groups_of(5).each do |g|
          -g.each do |game|
            - next if game.nil?
            .grid.text-center
              .game-thumb
                = link_to(image_tag("http://emulators.theoldcomputer.com/images/manufacturers_systems/MAME/ANDROID/365364mame-logo1.jpg", class: "game-image img-circle"), scoreboard_game_path(game))
                %h4.text-center
                  = game.name    

app/views/games/scoreboard.html.haml
%h1
  = button_link(@game.link, 'Go to Retro Uprising Page', 'btn-primary', 'blank')
  = button_link(games_path, "Back to Game List") 

.jumbotron
  %h1
    = @game.name
  /%p.small This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
  %p.small
    = sanitize(@game.dips)

.row
  .col-lg-8
    %table.table.table-striped.table-hover
      %thead
        %tr
          %th 
          %th Pos
          %th Player
          %th Team
          %th Score
          %th Points
      %tbody
        - points = 20
        - @players.each_with_index do |player, i|
          - @teamsf.find{|t| t[:id] == player.team_id}[:many] += 1
          %tr{ class: ("info" if cookies[:player_id].to_i == player.id)}
            %td
              = @teamsf.find{|t| t[:id] == player.team_id}[:many] < 6 ? image_tag("okicon.png", alt: "Qualified Score") : "" 
            %td
              = (@game.name == 'Contra' && player.max_score > 1000000) ? 1 : i + 1
            %td 
              = player.name
            %td 
              = player.team_name
            %td 
              = player.max_score  
            %td
              - if @teamsf.find{|t| t[:id] == player.team_id}[:many] < 6
                = points
                - points -= 1

  .col-lg-4
    .panel.panel-primary
      .panel-heading
        %h3.panel-title 
          Latest Submissions
      .list-group
        - @latest_sub.each do |submission|
          .list-group-item
            %span.badge
              = submission.score
            = submission.user.name

app/views/home/index.html.haml
%div{"ng-app"=>"scoreboard", "ng-view"=>""}

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Yolympics</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body id="<%= controller_name %>-<%= action_name %>">

  <div class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <span class="navbar-brand">
          <%= link_to(main_title, root_path) %> <%= image_tag('wolflogo.png', class: "brand-logo") %>
        </span>
      </div>
      <div class="navbar-collapse collapse navbar-responsive-collapse navbar-right">
        <ul class="nav navbar-nav">
          <li class="<%= controller_name == 'home' ? 'active' : '' %>"><%= link_to "Scoreboard", root_path %></li>
          <li class="<%= controller_name == 'games' ? 'active' : '' %>"><%= link_to "Games", games_path %></li>
          <li class="<%= controller_name == 'submissions' ? 'active' : '' %>"><%= link_to "Submit Score", submit_path %></li>
        </ul>
      </div>
    </div>
  </div>
  
  <div class="back-container" style = 'background: url("<%= @game.background_link if @game %>") no-repeat center; background-size: cover;'>
    <div class="container main-container <%= controller_name == 'games' && action_name == 'scoreboard' ? 'game-scoreboard' : '' %>">
      <%= render 'flash' %>
      <%= yield %>
    </div>
  </div>

  <%= render 'footer' %>

</body>
</html>

app/views/submissions/edit.html.haml
.page-header
  %h1.text-center Submit Score
.row
  .col-md-6.col-centered
    = simple_form_for(@submission, html: {class: "submission-form"})do |f|
      = f.association :user, collection: @players, label: "Player"
      = f.association :game, collection: @games, label: "Game"
      = f.input :score, label: "Score"
      = f.button :submit, "Submit", class: "btn-primary"

app/views/submissions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Submissions - Total: <%= @submissions.size %></h1>

<div class="col-lg-15 scoreboard">
  <table class="table table-striped table-hover main-scoreboard">
    <thead>
      <tr>
        <th>Date</th>
        <th>Player</th>
        <th>Team</th>
        <th>Game</th>
        <th>Score</th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% @submissions.each do |submission| %>
        <tr>
          <th><%= submission.created_at.strftime('%F %T') %></th>
          <th><%= submission.user.name %></th>
          <th><%= submission.user.team.name %></th>
          <th><%= submission.game.name %></th>
          <th><%= submission.score %></th>
          <td><%= link_to 'Edit', edit_submission_path(submission) %></td>
          <td><%= link_to 'Destroy', submission, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br>

app/views/submissions/new.html.haml
.page-header
  %h1.text-center Submit Score
.row
  .col-md-6.col-centered
    = simple_form_for(@submission, html: {class: "submission-form"})do |f|
      = f.association :user, collection: @players, label: "Player"
      = f.association :game, collection: @games, label: "Game"
      = f.input :score, label: "Score"
      = f.button :submit, "Submit", class: "btn-primary"

app/views/users/_form.html.haml
.row
  .col-md-6.col-centered
    = simple_form_for(@user) do |f|
      = f.error_notification
      = f.input :name, label: "Name"
      = f.association :team, collection: Team.all, label: "Team"
      = f.button :submit, "Submit", class: "btn-primary"

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Players - Total: <%= @users.size %></h1> <%= link_to 'Add Player', new_user_path %>


<div class="col-lg-15 scoreboard">
  <table class="table table-striped table-hover main-scoreboard">
    <thead>
      <tr>
        <th>Name</th>
        <th>Team</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <th><%= user.name %></th>
          <th><%= user.team.name %></th>
          <td><%= link_to 'Edit', edit_user_path(user) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br>

app/views/users/new.html.erb
<div class="page-header">
  <h1 class="text-center"> Submit Score </h1>
</div>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>